### ISSUE TITLE
Ability to specify timestamp parsing format

### ISSUE THREAD

**Issue by blah238** [couchcoding/Logbert#1]
First off, really cool viewer, great work! I'm not sure if you are still working on this or accepting issues/pull requests but figured I'd leave this here anyways.

I'm using the Custom File Receiver logger with a Columnizer that includes a Timestamp column type. The timestamps in the log files I'm viewing are in the format `yyyy-MM-dd HH:mm:ss,fff`, which is not correctly parsed, resulting in all the timestamps being displayed as `00:00:00`. The other columns (non-timestamp) are fine.

In the Options->General Settings I tried setting the Timestamp Format but it seems to only affect the output format, not the parsed format.

Looking at the code, I'm guessing the issue is on [this line](https://github.com/couchcoding/Logbert/blob/8e889a99b1206976a554effd710c9bd89d6f7ecc/src/Logbert/Logging/LogMessageCustom.cs#L140) where the value is being parsed but no format specification is specified so it just uses the current culture settings.

I'm not sure if it should be specified in the Columnizer settings or the general settings (probably the former since in theory one might have to deal with multiple different date formats).

Thanks!

**Comment by couchcoding** [comment]
Thanks for the report. The format should be specified for each custom parser.

**Comment by blah238** [comment]
This is awesome. Thank you!
