### ISSUE TITLE
How to configure .net core  log4net to udp

### ISSUE THREAD

**Issue by zh3305** [couchcoding/Logbert#10]
in .net core (2.2 or  3.0) log4net config XmlLayoutSchemaLog4j  Will not export any data.
How to configure  log4net  layout out to logbert Instead of using customization

**Comment by couchcoding** [comment]
This seems to be an issue of the .NET core implementation of log4net.. have you tried NLog as alternative?

**Comment by zh3305** [comment]
Yes! Nlog is work
