### ISSUE TITLE
64-bit LogBert?

### ISSUE THREAD

**Issue by leeand00** [couchcoding/Logbert#14]
If I want to use 64-bit LogBert, is there a package for that?  It seems a little slow.

Otherwise, maybe I could compile it for 64-bit with the correct set of directions? I had a 4MB log file and it took a while to parse it all, so I was thinking that maybe the issue is with the fact that it's running 32-bit (I'm unsure if it's single threaded or not).

I see it's written in C# and you likely used VS 20XX to compile it.

**Comment by couchcoding** [comment]
There're currently no 64-bit packages of Logbert. You can build a 64-Bit version on your own. Download the community edition of Visual Studio 2019 from Microsoft, load the solution, change the build configuration to 64-Bit (or AnyCPU) and rebuild all in release mode.

But I don't expect the files to load faster...

**Comment by leeand00** [comment]
> "But I don't expect the files to load faster..."

Any reason why?  I thought that's why everyone switched to 64-bit, so there's a wider data bus for loading things on.

**Comment by couchcoding** [comment]
I'll build the next version as AnyCPU. The JIT-Compiler will decide how to compile at runtime (x86 or x64).
