### ISSUE TITLE
What is the conversion pattern for log4net? 

### ISSUE THREAD

**Issue by bigdragon8899** [couchcoding/Logbert#20]
I can not find it in the document!
Please help.

**Comment by couchcoding** [comment]
What do you mean with 'conversion pattern'? Are you looking for a regular expression or for the log4net parser part in the Logbert [source code](https://github.com/couchcoding/Logbert/blob/ca74cd0b990650111d73c0638c1727d56cf526c2/src/Logbert/Logging/LogMessageLog4Net.cs#L241)?

**Comment by bigdragon8899** [comment]
```
    <appender name="udp" type="log4net.Appender.UdpAppender">
      <param name="Encoding" value="utf-8" />
      <RemoteAddress value="127.0.0.1" />
      <RemotePort value="7071" />
      <layout type="log4net.Layout.XmlLayout">
        <locationInfo value="true" />
      </layout>
    </appender>
```

I do not know how to setup in the app.config.

The above appender not work.

**Comment by couchcoding** [comment]
Please try another layout: `<layout type="log4net.Layout.XmlLayoutSchemaLog4j">`

**Comment by bigdragon8899** [comment]
Thank you ,it works!
