### ISSUE TITLE
Open log files on webserver

### ISSUE THREAD

**Issue by ChrisVanBael** [couchcoding/Logbert#21]
Hi,
Sorry if this is not the correct place to ask question, but I couldn't a forum or a way to contact you.

Is it somehow possible to open log files hosted on a webserver on the intranet?
For example: http://intranet.company.com/folder/logfile.log

just pasting this in on of the File Receivers gives a message that the file does not exist.

Next to that, is it also possible to apply some transformation rules on the log file?
Due to working on OpenVMS we were in the past not able to use more than 120 chars on a single line, so our files are hard wrapped at 120 chars. Would be nice if we could transform them when opening.

**Comment by couchcoding** [comment]
The 1.6.3.0 release contains a new HTTP file receiver. Transform received messages is currently not planned.
