### ISSUE TITLE
Cannot open simple Nlog file

### ISSUE THREAD

**Issue by raelb** [couchcoding/Logbert#23]
Trying to open a simple NLog file, displays an error:

![image](https://user-images.githubusercontent.com/13108198/178125473-b1ca22e4-0e5f-4717-b790-b6210328748c.png)

File I am trying to open:
[NLogFile.log](https://github.com/couchcoding/Logbert/files/9078049/NLogFile.log)

I've compiled project from recent sources...

**Comment by couchcoding** [comment]
This is because the provided log file is not in `chainsaw` format. You may create a new custom log receiver for this log file format. Please see my solution in issue #15 for more details.

**Comment by snakefoot** [comment]
NLog can output in chainsaw format, when specifying layout:

```xml
<target type="file" name="logfile" layout="${log4jxmlevent}" />
```

See also: https://github.com/NLog/NLog/wiki/Log4JXMLEvent-Layout-Renderer

**Comment by raelb** [comment]
Thanks that helped me :)
