### ISSUE TITLE
Missing logger configuration persistence

### ISSUE THREAD

**Issue by marnef** [couchcoding/Logbert#5]
Thank you very much for this excellent project! There is just one feature I'm missing, missing it so much that I can't use the software on a daily basis: The configuration of the logger (type, port, adapter) is not stored, meaning that I have to configure it after every start of the application. Also if I use different logger configurations I can't re-establish them by loading a previous configuration.

**Comment by couchcoding** [comment]
Which logger did you use?

**Comment by marnef** [comment]
NLog TCP Receiver. But does that matter?
